---
name: TF

on: [push, workflow_dispatch]

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set GH token
        run: |
          echo 'Using GitHub access token to authorize in other repositories...'
          git config --global url."https://${TOKEN}@github.com".insteadOf https://github.com
          echo 'GitHub access token mounted'
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: TF init
        run: |
          terraform init

      - name: TF plan
        run: |
          terraform plan -var="region=${REGION}"
        env:
          REGION: ${{ secrets.REGION }}
