---
name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set GH token
        run: |
          echo 'Using GitHub access token to authorize in other repositories...'
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com
          
      - name: TF init
        run: |
          terraform init
